Repository fga-eps-mds/2019.2-Gymnasteg-Frontend, pull requests merged in 2019-11, with the labels that each got.

#29 Correção de bug do Travis CI
  .travis.yml
Labels: Devops, bug

#27 Feature/114 us13#dashboard do arbitro
  .env
  package.json
  src/App.jsx
  src/Components/Layout/PageContent/PageContent.jsx
  src/Services/authentication/index.js
  src/Views/Dashboard/Judge/Bancas/Bancas.css
  src/Views/Dashboard/Judge/Bancas/Bancas.jsx
  src/Views/Dashboard/Judge/Bancas/closestDateToToday.js
  src/Views/Dashboard/Judge/Bancas/index.js
  src/Views/Dashboard/Page/Drawer/Drawer.jsx
  yarn.lock
Labels: bug, enhancement

#30 Configurar Codecov
  README.md
  codecov.yml
Labels: Devops, enhancement

#42 Feature/52 US10# Votação
  src/App.jsx
  src/Components/Countdown/Countdown.jsx
  src/Components/Countdown/index.js
  src/Components/JudgeVotesList/JudgeVotesList.jsx
  src/Components/JudgeVotesList/JudgeVotesList.styles.js
  src/Components/JudgeVotesList/index.js
  src/Components/NameWithSex/NameWithSex.jsx
  src/Components/NameWithSex/index.js
  src/Components/RemainingTimeBanner/RemainingTimeBanner.jsx
  src/Components/RemainingTimeBanner/RemainingTimeBanner.styles.js
  src/Components/RemainingTimeBanner/index.js
  src/Components/SexIcon/SexIcon.jsx
  src/Components/SexIcon/SexIcon.styles.js
  src/Components/SexIcon/index.js
  src/Components/TotalScoreDisplayer/TotalScoreDisplayer.jsx
  src/Components/TotalScoreDisplayer/TotalScoreDisplayer.styles.js
  src/Components/TotalScoreDisplayer/index.js
  src/Components/VotingJudgesList/VotingJudgesList.jsx
  src/Components/VotingJudgesList/VotingJudgesList.styles.js
  src/Components/VotingJudgesList/index.js
  src/Services/authentication/index.js
  src/Services/authentication/index.test.js
  src/Views/Dashboard/Admin/CadastroArbitrosForm/CadastroArbitrosForm.jsx
  src/Views/Dashboard/Admin/Ranking/Ranking.jsx
  src/Views/Dashboard/Admin/Ranking/RankingModal.js
  src/Views/Dashboard/Admin/Ranking/index.js
  src/Views/Dashboard/Judge/Bancas/Bancas.css
  src/Views/Dashboard/Judge/Bancas/Bancas.jsx
  src/Views/Dashboard/Judge/Bancas/Bancas.styles.js
  src/Views/Dashboard/Judge/Votacao/Votacao.jsx
  src/Views/Dashboard/Judge/Votacao/Votacao.styles.js
  src/Views/Dashboard/Judge/Votacao/index.js
  src/Views/Dashboard/Page/Drawer/Drawer.jsx
  src/socket-context.js
Labels: bug, enhancement
